name: "Setup Devenv"
description: "Prepares image with packages and cleanup"
runs:
  using: "composite"
  steps:
    - name: Show CPU Model and Free Space
      shell: bash
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        free -h
    
    - name: check disk space
      shell: bash
      run: |
        df -h
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      shell: bash
      run: |
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev 
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        df -h
