#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT

name: NanoPi Test

on:
  workflow_dispatch:
    inputs:
      openwrt_branch:
        description: 'OpenWrt Branch to build'     
        required: true
        default: '21.02'
        type: choice
        options:
        - '21.02'
      nanopi_model:
        description: 'NanoPi Model'     
        required: true
        default: 'R2S'
        type: choice
        options:
        - R2S
        - R4S
      release_id:
        description: 'Release Id Suffix : 20220101.suffix'
        required: true
        default: '1'
        type: string
        
jobs:
  init:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    # Map a step output to a job output
    outputs:
      build_date: ${{ steps.gen_build_date.outputs.build_date }}
    steps:
    - id: gen_build_date
      run: echo "::set-output name=build_date::$(date +%Y.%m.%d)"
  job2:
    runs-on: ubuntu-20.04
    needs: init
    steps:
    - run: echo ${{ needs.init.outputs.build_date }}
